# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_password
      POSTGRES_DB: flask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
